language: node_js
node_js:
  - "12"
env:
  - REDIS_PORT=${REDIS_PORT} REDIS_PASSWORD=${REDIS_PASSWORD}
before_script:
  - sudo redis-server /etc/redis/redis.conf --port ${REDIS_PORT} --requirepass "${REDIS_PASSWORD}"
script:
  - npm install
  - npm run test
after_success:
  - npm run coverage
after_failure:
  - npm run coverage